### ISSUE TITLE
LMAO UR HISTORY TEACHER

### ISSUE THREAD

**Issue by VulcanWM** [JBYT27/10-minute-flask-tutorial-#1]
okay this isnt a bug or anything ~~it's legit a tutorial~~ but lemme just say again, stan ur history teacher

**Comment by JBYT27** [comment]
HAHAHAHAHAHA, YEAHHH, STAN HISTORY TEACHER!!

**Comment by VulcanWM** [comment]
YEAH OKAY ILL CLOSE THIS NOW LMAO

**Comment by JBYT27** [comment]
HAHA OKAY
> STAN HISTORY TEACHER

**Comment by VulcanWM** [comment]
YES #STANURHISTORYTEACHER

**Comment by JBYT27** [comment]
YEEESSSSS
